name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn 
      
      - name: Build
        run:  yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist